### ISSUE TITLE
Attachment multipart upload

### ISSUE THREAD

**Issue by ggrebert** [before-interop/common#17]
Ajouter des endpoints à l'API Attachment afin d'autoriser l'envoi de fichiers en mode "multipart".

Cette fonctionnalité permettrait:

- l'envoi de fichier volumineux
- l'accélération d'un upload par asynchronisme
- contournerait les limites de certains serveurs web qui limitent par défaut le body à 10Mo voir moins

Elle serait utile pour les protocoles suivants:

- [AnomalieAdresse](https://github.com/before-interop/anomalieAdresse) pour l'envoi de fichier PDF volumineux lors de demande de création d'un nouveau bâtiment
- [Malfacon](https://github.com/before-interop/malfacon) pour l'envoi de photo en très haute résolution, ce qui permettrait de faciliter les analyses par IA

**Comment by richard-olvera** [comment]
ajouter dans le post attachment si content-type="application/json" en retour on ajoute la taille  max du chunk
