### ISSUE TITLE
Add Json operator in filters

### ISSUE THREAD

**Issue by ggrebert** [before-interop/common#22]
Il est très difficile, voir impossible de filtrer sur les relatedEntity si celle-ci sont multiples.

Exemple:

```json
[
  {
    "relatedEntity": [
      {
        "referredType": "PM",
        "referredId": "1"
      },
      {
        "referredType": "PBO",
        "referredId": "1"
      }
    ]
  },
  {
    "relatedEntity": [
      {
        "referredType": "PM",
        "referredId": "2"
      },
      {
        "referredType": "PBO",
        "referredId": "1"
      }
    ]
  }
]
```

Si je veux rechercher les ressources qui matchent avec `referredType` à `PM` dont l'id est `1` la requête suivante est incohérente car elle me retourne tout les éléments du au fait qu'une `PBO` porte le même id qu'un `PM`.

`?relatedEntity.referredType=PM&relatedEntity.id=1`

Il faudrait un filter json qui vérifie l'égalité sur un ensemble.

**Comment by alexisthethe** [comment]
Je ne comprends pas l'exemple que tu expose...
Pourquoi on aurait des relatedEntity multiples ?
Dans un TroubleTicket on a un champ relatedEntity qui est une liste et ça s'arrête là.

On a plutôt ça
```
    "relatedEntity": [
      {
        "referredType": "PM",
        "referredId": "1"
      },
      {
        "referredType": "PBO",
        "referredId": "1"
      },
      {
        "referredType": "PM",
        "referredId": "2"
      },
      {
        "referredType": "PBO",
        "referredId": "1"
      }
   ]
```

**Comment by ggrebert** [comment]
Mon exemple représentait un exemple avec 2 trouble tickets.
J'ai simplifié le code en ne gardant que la clé relatedEntity.

On a donc bien un tableau de trouble ticket qui contient 2 éléments qui font chacun relié à 2 entité externe.

Et le protocole ne permet de filtrer correctement pour récupérer que le premier élément et faisant une jointure sur un id particulier et avec un type à PM.

**Comment by alexisthethe** [comment]
Ok je comprends la problématique à présent. Merci.
Ça donnerait quoi avec un opérateur json ?

**Comment by ggrebert** [comment]
la diff c'est que je ne cherche plus sur les clé 'nested' mais sur la clé parente (ici relatedEntity)
je cherche si relatedEntity a un élément du tableau qui correspond au json donné
