### ISSUE TITLE
fix: remove 3-item allOf by merging addressable to entity

### ISSUE THREAD

**Issue by hamdan-ahmad-lb** [before-interop/common#46]
3-item `allOf` are not supported by codegens because they violate the single-parent principle. For inheritance, we should use a 2-item `allOf` where the first is a `$ref` and the second is an inline schema.

In our case, the 3-item `allOf` is used in the `Entity` and `EntityRef` schemas where they extend `Extensible` and `Addressable`, and defines their own properties. Here, we have the following observations:
1. The fields defined in `Addressable` and in the inline schema of the `Entity` are the same, which means it does not need to extend `Addressable`.
2. `Addressable` is only used by `Entity` - which does not need, as we mentioned above - and the `EntityRef` schema.
3. `EntityRef` extends `Extensible` and `Addressable`, which as concluded from the above is identical to extending `Entity`.

Following these observations, we can see that:
1. There is no practical, valid use of `Addressable`.
2. `Addressable` can be merged with `Entity` to avoid 3-item `allOf`.
3. `EntityRef` can extend `Entity` instead on `Extensible` and `Addressable`.

**Comment by vmeunier** [comment]
It is TMF Compliant, they designed the TroubleTicket "as-is" :)
