### ISSUE TITLE
Mettre en cohérence les critères "read only" des champs relatedEntity des types d'ano NewBuilding/Modification/nbLogements avec ceux des autres champs obligatoires à la création

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/common#7]
Dans l'existant Anomalie adresse:

les champs relatedEntity des types d'ano NewBuilding/Modification/nbLogements, saisis par l'OC à la création de l'AA, sont read-only
les champs code_oi, code_oc, saisis par l'OC à la création de l'AA, ne sont pas read-only

==> ceci n'est pas cohérent ==> merci de remettre en cohérence ces critères

**Comment by ggrebert** [comment]
Ce repository sert uniquement de base commune aux différents protocoles interop.
Pour créer une issue pout le protocole AnomalieAdresse, merci d'utiliser le repository adéquat: https://github.com/before-interop/anomalieAdresse
