### ISSUE TITLE
Complexity : prévoir la valeur vide pour les anomalies en masse

### ISSUE THREAD

**Issue by JeanChristopheLacroix** [before-interop/common#9]
La description word du protocole prévoit que la complexité simple/complexe ne soit définie que pour les anomalies unitaires.
La complexité n'est pas définie pour les anos en masse 
Cf PJ
Merci de prévoir la possibilité de mettre un valeur vide, ça n'est pas prévu dans la version actuelle du swagger

**Comment by JeanChristopheLacroix** [comment]
![Description protocole AA](https://github.com/before-interop/common/assets/138661009/cf382bf5-2702-49cd-a380-9156414145fb)

**Comment by JeanChristopheLacroix** [comment]
![image](https://github.com/before-interop/common/assets/138661009/cef9f6ec-3945-4d00-838c-f7facb3f32fd)

**Comment by ggrebert** [comment]
Ce repository sert uniquement de base commune aux différents protocoles interop.
Pour créer une issue pout le protocole AnomalieAdresse, merci d'utiliser le repository adéquat: https://github.com/before-interop/anomalieAdresse
